import React, { useState, useRef, useMemo } from 'react';
import ReactMarkdown from 'react-markdown';
import { Printer, Download, ArrowLeft, HelpCircle, Palette, Image as ImageIcon, Edit3, Save, Upload, FolderDown, PlusSquare, Table, AlertTriangle, Terminal, Grid, List, ChevronRight, FileJson, Camera, CircuitBoard, RefreshCw, Trash2 } from 'lucide-react';
import { ManualTheme, ManualConfig, SavedProject } from '../types';

interface ManualPreviewProps {
  content: string;
  config: ManualConfig;
  onContentChange: (newContent: string) => void;
  onBack: () => void;
  theme: ManualTheme;
  onThemeChange: (theme: ManualTheme) => void;
}

// --- COVER PAGE COMPONENT ---
const CoverPage = ({ theme, title, date }: { theme: ManualTheme, title: string, date: string }) => {
  const brandName = title || "MANUÁL ZARIADENIA";
  const year = new Date().getFullYear();

  // STYLES: Adapted for safe 15mm margin print. Height is constrained to ~260mm to fit on one page.
  switch (theme) {
    case 'industrial':
      return (
        <div className="print-cover w-full h-[260mm] bg-[#e5e5e5] relative flex flex-col justify-between p-8 border-r-[12px] border-orange-600 font-mono break-after-page page-break-after-always">
          <div className="border-t-[8px] border-orange-600 w-full pt-12">
            <h1 className="text-5xl font-black text-gray-900 uppercase leading-none tracking-tighter mb-4 break-words">{brandName}</h1>
            <div className="text-xl font-bold text-orange-600 uppercase tracking-widest">Technická Dokumentácia</div>
          </div>
          <div className="border-4 border-gray-800 p-8 bg-[#1a1a1a] text-white">
             <div className="grid grid-cols-2 gap-4 text-sm">
                <div className="text-gray-400">ID PROJEKTU:</div>
                <div className="font-bold text-green-400 text-right">{Math.floor(Math.random() * 10000)}</div>
                <div className="text-gray-400">DÁTUM:</div>
                <div className="font-bold text-green-400 text-right">{date}</div>
                <div className="text-gray-400">VERZIA:</div>
                <div className="font-bold text-green-400 text-right">1.0 / {year}</div>
             </div>
          </div>
          <div className="text-xs text-gray-500 uppercase">
             Generated by Elift ManualGen • Industrial Standard
          </div>
        </div>
      );
    case 'swiss':
      return (
        <div className="print-cover w-full h-[260mm] bg-white relative flex flex-col p-8 font-sans break-after-page page-break-after-always border border-gray-100">
          <div className="flex-1 flex flex-col justify-center">
             <div className="bg-[#dc2626] text-white w-20 h-20 flex items-center justify-center font-black text-4xl mb-12">
               +
             </div>
             <h1 className="text-6xl font-black text-black leading-[0.9] tracking-tighter mb-8 break-words">
               {brandName.split(' ').map((word, i) => <div key={i}>{word}</div>)}
             </h1>
             <div className="h-2 w-20 bg-black mb-8"></div>
             <h2 className="text-2xl font-bold text-gray-500">Užívateľský a Servisný Manuál</h2>
          </div>
          <div className="border-t-2 border-black pt-4 flex justify-between text-sm font-bold">
            <span>{date}</span>
            <span>REV. 1.0</span>
            <span>SÉRIA {year}</span>
          </div>
        </div>
      );
    case 'elegant':
        return (
          <div className="print-cover w-full h-[260mm] bg-[#fafcfb] relative flex flex-col items-center justify-center p-8 font-serif text-center border-double border-4 border-emerald-900 m-0 break-after-page page-break-after-always">
             <div className="w-full h-full flex flex-col items-center justify-center border border-emerald-100 p-12">
                <div className="text-emerald-800 italic text-xl mb-8">Dokumentácia</div>
                <h1 className="text-5xl text-emerald-900 font-medium italic mb-12 break-words max-w-full">{brandName}</h1>
                <div className="w-16 h-16 border rounded-full flex items-center justify-center border-emerald-200 mb-12">
                   <div className="w-12 h-12 border rounded-full border-emerald-800"></div>
                </div>
                <div className="text-sm text-emerald-700 tracking-widest uppercase mt-24">
                  {date} • Verzia 1.0
                </div>
             </div>
          </div>
        );
    case 'construction':
        return (
          <div className="print-cover w-full h-[260mm] bg-yellow-400 relative flex flex-col justify-between p-8 font-sans break-after-page page-break-after-always">
             <div className="border-8 border-black h-full flex flex-col justify-between p-8 bg-white shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
                <div className="bg-black text-yellow-400 p-4 inline-block self-start font-black text-xl uppercase transform -skew-x-12">
                   POZOR: MANUÁL
                </div>
                
                <div className="text-center">
                   <h1 className="text-6xl font-black text-black uppercase leading-none mb-4 break-words">{brandName}</h1>
                   <div className="bg-black h-4 w-full pattern-stripes"></div>
                </div>

                <div className="grid grid-cols-2 border-t-4 border-black pt-4">
                   <div className="font-bold">DÁTUM VYDANIA:</div>
                   <div className="text-right font-mono">{date}</div>
                   <div className="font-bold">URČENÉ PRE:</div>
                   <div className="text-right font-mono">TECHNIKOV</div>
                </div>
             </div>
          </div>
        );
    case 'modern':
    default:
      return (
        <div className="print-cover w-full h-[260mm] bg-gradient-to-br from-brand-900 to-brand-700 relative flex flex-col justify-center p-8 text-white font-sans break-after-page page-break-after-always rounded-sm">
           <div className="absolute top-0 left-0 w-full h-full opacity-10 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')]"></div>
           <div className="z-10">
             <div className="text-brand-200 uppercase tracking-[0.2em] mb-4 text-sm font-semibold">Oficiálna Dokumentácia</div>
             <h1 className="text-5xl font-bold mb-6 leading-tight break-words">{brandName}</h1>
             <div className="w-20 h-2 bg-brand-400 mb-12 rounded-full"></div>
             
             <div className="bg-white/10 backdrop-blur-sm p-8 rounded-xl border border-white/20 max-w-md">
                <div className="grid grid-cols-[auto_1fr] gap-x-8 gap-y-4 text-sm">
                   <span className="text-brand-200">Dátum</span>
                   <span className="font-mono">{date}</span>
                   
                   <span className="text-brand-200">Verzia</span>
                   <span className="font-mono">1.0.0</span>
                   
                   <span className="text-brand-200">Jazyk</span>
                   <span className="font-mono">Slovenský</span>
                </div>
             </div>
           </div>
           <div className="absolute bottom-8 right-8 text-right z-10">
              <div className="text-4xl font-black text-white/20">ELIFT</div>
           </div>
        </div>
      );
  }
}

// --- VISUAL COMPONENTS (POWERED BY JSON) ---

// 1. Keypad Key Component
const KeyCap: React.FC<{ text: string, themeClasses: any }> = ({ text, themeClasses }) => {
  const isEnter = ['↵', 'ENTER', 'Enter'].includes(text);
  const isVar = ['x', 'y', 'X', 'Y', 'N', 'n', '...'].includes(text);
  
  if (isEnter) {
    return <span className={`inline-flex items-center justify-center h-6 px-2 text-[10px] font-black uppercase tracking-wider rounded shadow-sm border mx-0.5 ${themeClasses.enterKey}`}>ENTER</span>;
  }
  if (isVar) {
     return <span className="inline-flex items-center justify-center min-w-[1.5rem] h-6 px-1 text-xs italic font-serif text-gray-500 bg-gray-100 border border-gray-300 rounded mx-0.5">{text}</span>;
  }
  return <span className={`inline-flex items-center justify-center min-w-[1.5rem] h-6 px-1 text-xs font-bold border-b-2 rounded mx-0.5 ${themeClasses.keycap}`}>{text}</span>;
};

// 2. Custom Table of Contents Component (JSON)
const TocComponent = ({ data, themeClasses }: { data: any[], themeClasses: any }) => {
  if (!Array.isArray(data)) return <div className="text-red-500 bg-red-50 p-2 text-xs border border-red-200 rounded">Chyba v dátach obsahu (očakávané pole)</div>;

  return (
    <div className="not-prose my-10 w-full">
      <h4 className={`text-center text-lg font-black uppercase tracking-widest mb-8 border-b-2 border-gray-900 pb-2 ${themeClasses.strong.split(' ')[0]}`}>Obsah</h4>
      <div className="flex flex-col gap-0.5 w-full">
        {data.map((item, idx) => (
          <div key={idx} className="toc-row break-inside-avoid page-break-inside-avoid">
            <span className="toc-title text-sm">{item.chapter}</span>
            <span className="toc-dots"></span>
            <span className="toc-page text-sm">{item.page}</span>
          </div>
        ))}
      </div>
    </div>
  );
};

// 3. Custom Menu Component (JSON)
const MenuComponent = ({ data, themeClasses }: { data: any[], themeClasses: any }) => {
  if (!Array.isArray(data)) return <div className="text-red-500 bg-red-50 p-2 text-xs border border-red-200 rounded">Chyba v dátach menu (očakávané pole)</div>;

  return (
    <div className="not-prose my-8 w-full border border-gray-200 rounded-lg overflow-hidden shadow-sm">
      <div className="bg-gray-50 border-b border-gray-200 px-4 py-2 flex justify-between text-xs font-bold text-gray-500 uppercase tracking-wider">
        <span>Cesta / Položka</span>
        <span>Popis</span>
      </div>
      <div className="divide-y divide-gray-100 bg-white">
        {data.map((item, idx) => {
          const levels = item.path || [];
          return (
            <div key={idx} className="flex flex-col sm:flex-row sm:items-center p-3 sm:px-4 sm:py-2 hover:bg-blue-50/30 transition-colors break-inside-avoid page-break-inside-avoid">
              <div className="flex-1 flex flex-wrap items-center gap-1 mb-1 sm:mb-0">
                {levels.map((lvl: string, lIdx: number) => (
                  <React.Fragment key={lIdx}>
                    {lIdx > 0 && <ChevronRight className="w-3 h-3 text-gray-300" />}
                    <span className={`text-sm ${lIdx === levels.length - 1 ? 'font-bold text-gray-800' : 'text-gray-500'}`}>
                      {lvl}
                    </span>
                  </React.Fragment>
                ))}
              </div>
              {item.description && (
                <div className="sm:w-1/2 text-sm text-gray-600 pl-4 border-l border-gray-100 italic">
                  {item.description}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};

// 4. Custom Keypad Component (JSON)
const KeypadComponent = ({ data, themeClasses }: { data: any[], themeClasses: any }) => {
  if (!Array.isArray(data)) return <div className="text-red-500 bg-red-50 p-2 text-xs border border-red-200 rounded">Chyba v dátach klávesnice (očakávané pole)</div>;

  return (
    <div className="not-prose my-8 w-full bg-[#f8f9fa] border border-gray-200 rounded-lg p-1">
      <table className="w-full border-collapse">
         <thead>
             <tr className="text-left text-xs text-gray-400 uppercase tracking-wider border-b border-gray-200">
                 <th className="p-3 font-medium">Vstup / Kód</th>
                 <th className="p-3 font-medium">Funkcia</th>
                 <th className="p-3 font-medium">Poznámka</th>
             </tr>
         </thead>
         <tbody className="bg-white divide-y divide-gray-100">
            {data.map((item, idx) => {
                const inputKeys = item.inputs ? String(item.inputs).split(' ') : [];
                return (
                    <tr key={idx} className="hover:bg-gray-50 break-inside-avoid page-break-inside-avoid">
                        <td className="p-3 align-middle">
                            <div className="flex flex-wrap gap-0.5">
                                {inputKeys.map((k: string, ki: number) => <KeyCap key={ki} text={k} themeClasses={themeClasses} />)}
                            </div>
                        </td>
                        <td className="p-3 text-sm font-bold text-gray-800 align-middle">{item.function}</td>
                        <td className="p-3 text-sm text-gray-500 italic align-middle">{item.note}</td>
                    </tr>
                )
            })}
         </tbody>
      </table>
    </div>
  );
};

// 5. Generic Table Component (JSON)
const TableComponent = ({ data, themeClasses }: { data: any, themeClasses: any }) => {
  if (!data || !data.headers || !data.rows) return <div className="text-red-500 bg-red-50 p-2 text-xs border border-red-200 rounded">Chyba v dátach tabuľky</div>;

  return (
    <div className={`not-prose w-full ${themeClasses.tableContainer} manual-table-root`}>
      <table className={themeClasses.table}>
        <thead className={themeClasses.tableHeader}>
          <tr>
            {data.headers.map((h: string, i: number) => (
                <th key={i} className={themeClasses.tableTh}>{h}</th>
            ))}
          </tr>
        </thead>
        <tbody className={themeClasses.tableBody}>
          {data.rows.map((row: string[], rI: number) => (
            <tr key={rI} className={`${rI % 2 !== 0 ? themeClasses.tableRowEven : ""} break-inside-avoid page-break-inside-avoid`}>
               {row.map((cell: string, cI: number) => (
                 <td key={cI} className={themeClasses.tableTd}>{cell}</td>
               ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

// 6. Smart Image Component (JSON)
const ImageBlockComponent = ({ data, themeClasses, onUpload }: { data: any, themeClasses: any, onUpload: (file: File) => void }) => {
  if (!data) return null;
  const Icon = data.type === 'diagram' ? CircuitBoard : Camera;

  return (
    <div className="not-prose w-full my-8 break-inside-avoid page-break-inside-avoid print:hidden image-block">
       <figure className="flex flex-col items-center w-full">
         <label className={`w-full relative flex flex-col items-center justify-center min-h-[160px] cursor-pointer ${themeClasses.imagePlaceholder}`}>
            <input type="file" accept="image/*" className="hidden" onChange={(e) => {
                 if(e.target.files?.[0]) onUpload(e.target.files[0]);
            }} />
            <Icon className="w-10 h-10 text-gray-300 mb-2" />
            <span className="font-bold text-gray-500 group-hover:text-gray-800 transition-colors">
              {data.type === 'diagram' ? 'Vložiť Diagram / Schému' : 'Vložiť Fotografiu'}
            </span>
            <div className="text-xs text-gray-400 mt-2 px-8 italic">"{data.description || 'Žiadny popis'}"</div>
            <div className="absolute top-2 right-2 bg-white px-2 py-1 rounded border shadow-sm text-[10px] font-mono text-gray-400 uppercase">AUTO-ID: {data.type}</div>
         </label>
         {data.caption && (
            <figcaption className="mt-3 text-sm text-gray-600 font-medium italic text-center w-full max-w-[80%] border-b border-gray-100 pb-2">{data.caption}</figcaption>
         )}
       </figure>
    </div>
  );
};


const ManualPreview: React.FC<ManualPreviewProps> = ({ content, config, onContentChange, onBack, theme, onThemeChange }) => {
  const [isEditing, setIsEditing] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  
  // Get the brand name for the cover page (default to Elift if not found)
  const brandName = config.replacements[0]?.replacement || "Elift Solutions";

  // SANITIZE CONTENT
  const safeContent = useMemo(() => {
    return content.replace(/<div style='page-break-before: always;'><\/div>/g, '\n\n---\n\n');
  }, [content]);

  const handlePrint = () => {
    const originalTitle = document.title;
    const cleanBrand = brandName.replace(/[^a-zA-Z0-9]/g, '');
    const timestamp = new Date().toISOString().slice(0, 10);
    document.title = `Manual_${cleanBrand}_${theme}_${timestamp}`;
    window.print();
    setTimeout(() => { document.title = originalTitle; }, 500);
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([safeContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `manual_elift_${theme}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleSaveProject = () => {
    const currentConfig = { ...config, theme };
    const projectData: SavedProject = {
      version: "1.0",
      timestamp: Date.now(),
      config: currentConfig,
      content: safeContent
    };
    const blob = new Blob([JSON.stringify(projectData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `projekt_elift_${new Date().toISOString().slice(0,10)}.elift`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Image replacement handler
  const handleReplaceImage = (oldSrc: string, newFile: File) => {
    const reader = new FileReader();
    reader.onload = () => {
      const newBase64 = reader.result as string;
      const newContent = content.replace(oldSrc, newBase64);
      onContentChange(newContent);
    };
    reader.readAsDataURL(newFile);
  };

  // Insert Text Handler
  const insertTextAtCursor = (textToInsert: string) => {
    if (!textareaRef.current) return;
    const textarea = textareaRef.current;
    const start = textarea.selectionStart;
    const end = textarea.selectionEnd;
    const newText = content.substring(0, start) + textToInsert + content.substring(end);
    onContentChange(newText);
    setTimeout(() => {
      textarea.focus();
      textarea.setSelectionRange(start + textToInsert.length, start + textToInsert.length);
    }, 0);
  };

  // Smart Image Upload
  const handleSmartImageUpload = (originalRawContent: string, file: File) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64String = reader.result as string;
      let caption = "Obrázok";
      let targetObj: any = null;
      try {
          targetObj = JSON.parse(originalRawContent);
          if (targetObj.caption) caption = targetObj.caption;
      } catch(e) { console.warn("Invalid JSON"); }

      const newImageMarkdown = `\n![${caption}](${base64String})\n*${caption}*\n`;
      const regex = /```json:image([\s\S]*?)```/g;
      let match;
      let newContent = content;
      let found = false;

      while ((match = regex.exec(content)) !== null) {
          const fullBlockStr = match[0];
          const innerJsonStr = match[1];
          let isMatch = false;
          if (targetObj) {
            try {
                const blockObj = JSON.parse(innerJsonStr);
                if (JSON.stringify(sortObj(blockObj)) === JSON.stringify(sortObj(targetObj))) isMatch = true;
            } catch (e) {}
          } else {
             if (innerJsonStr.replace(/\s+/g, '').trim() === originalRawContent.replace(/\s+/g, '').trim()) isMatch = true;
          }
          if (isMatch) {
              const startIndex = match.index;
              const endIndex = startIndex + fullBlockStr.length;
              newContent = content.substring(0, startIndex) + newImageMarkdown + content.substring(endIndex);
              found = true;
              break;
          }
      }
      if (found) onContentChange(newContent);
      else alert("Nepodarilo sa nájsť tento blok.");
    };
    reader.readAsDataURL(file);
  };
  
  const sortObj = (o: any): any => {
    if (typeof o !== 'object' || o === null) return o;
    if (Array.isArray(o)) return o.map(sortObj);
    return Object.keys(o).sort().reduce((r: any, k) => {
        r[k] = sortObj(o[k]);
        return r;
    }, {});
  };

  const handlePaste = (e: React.ClipboardEvent<HTMLTextAreaElement>) => {
    const items = e.clipboardData.items;
    for (let i = 0; i < items.length; i++) {
      if (items[i].type.indexOf('image') !== -1) {
        e.preventDefault();
        const blob = items[i].getAsFile();
        if (blob) {
          const reader = new FileReader();
          reader.onload = (event) => {
            const base64 = event.target?.result as string;
            const imageMarkdown = `\n![Vložený obrázok](${base64})\n`;
            const textarea = e.currentTarget;
            const start = textarea.selectionStart;
            const end = textarea.selectionEnd;
            const newContent = content.substring(0, start) + imageMarkdown + content.substring(end);
            onContentChange(newContent);
          };
          reader.readAsDataURL(blob);
        }
      }
    }
  };

  const insertTemplates = {
    tocTable: `
\`\`\`json:toc
[
  {"chapter": "1. Úvod", "page": 5},
  {"chapter": "2. Bezpečnosť", "page": 8},
  {"chapter": "3. Inštalácia", "page": 12}
]
\`\`\`
`,
    menuTable: `
\`\`\`json:menu
[
  {"path": ["HLAVNÉ", "Nastavenia", "Čas"], "description": "Nastavenie hodín systému"},
  {"path": ["HLAVNÉ", "Displej"], "description": "Jas a kontrast"}
]
\`\`\`
`,
    keypadTable: `
\`\`\`json:keypad
[
  {"inputs": "1 0 0 ENTER", "function": "Volanie na poschodie", "note": "Zadajte číslo"},
  {"inputs": "MENU ENTER", "function": "Vstup do menu", "note": "Iba servis"}
]
\`\`\`
`,
    standardTable: `
\`\`\`json:table
{
  "headers": ["Parameter", "Hodnota", "Jednotka"],
  "rows": [
    ["Napätie", "230", "V"],
    ["Prúd", "10", "A"]
  ]
}
\`\`\`
`,
    imageJson: `
\`\`\`json:image
{
  "caption": "Obr. 1: Popis obrázku",
  "description": "Technický nákres zariadenia",
  "type": "diagram"
}
\`\`\`
`,
    alertInfo: `\n> [!NOTE]\n> **UPOZORNENIE:** Sem napíšte dôležitú informáciu pre technika.\n`,
    alertDanger: `\n> [!WARNING]\n> **NEBEZPEČENSTVO:** Práce pod napätím! Dodržujte BOZP.\n`
  };

  const getThemeClasses = () => {
    switch (theme) {
      case 'swiss':
        return {
          wrapper: "font-sans",
          h1: "text-5xl font-black text-gray-900 tracking-tighter mb-8 pt-4 uppercase leading-none break-after-avoid",
          h2: "text-2xl font-bold text-gray-900 mt-12 mb-6 flex items-center gap-4 before:content-[''] before:block before:w-6 before:h-6 before:bg-[#dc2626] break-after-avoid",
          h3: "text-lg font-bold text-[#dc2626] mt-8 mb-4 uppercase tracking-widest border-b border-gray-200 pb-1 break-after-avoid",
          tableContainer: "my-8 w-full border-t-4 border-[#dc2626] bg-white shadow-sm overflow-x-auto",
          table: "w-full border-collapse text-left",
          tableHeader: "bg-gray-100 text-[#dc2626] font-black text-xs uppercase tracking-widest border-b-2 border-[#dc2626]",
          tableTh: "px-4 py-3 border border-gray-300 align-bottom",
          tableBody: "bg-white",
          tableRowEven: "bg-gray-50",
          tableTd: "px-4 py-2 text-sm text-gray-900 font-medium align-top leading-relaxed border border-gray-300",
          keycap: "bg-white border-gray-300 text-gray-800 shadow-sm",
          enterKey: "bg-[#dc2626] text-white border-[#b91c1c]",
          blockquote: "border-l-[6px] border-[#dc2626] bg-gray-50 text-gray-900 p-6 my-8 font-medium italic shadow-sm",
          code: "bg-gray-100 text-[#dc2626] px-1.5 py-0.5 rounded-sm font-mono text-sm font-bold border border-gray-200",
          strong: "text-gray-900 font-black",
          link: "text-[#dc2626] hover:text-[#b91c1c] underline decoration-2 underline-offset-2",
          imagePlaceholder: "bg-gray-100 border-2 border-dashed border-[#dc2626] p-6 my-6 flex flex-col items-center justify-center text-center rounded-lg transition-all hover:bg-red-50 cursor-pointer group shadow-sm hover:shadow-md hover:border-red-400"
        };
      case 'industrial':
        return {
          wrapper: "font-mono bg-[#e5e5e5]",
          h1: "text-3xl font-black text-gray-900 uppercase border-b-4 border-orange-600 pb-4 mb-8 tracking-tight break-after-avoid",
          h2: "text-2xl font-bold text-gray-900 border-l-[12px] border-orange-600 pl-4 uppercase tracking-wide mt-10 mb-6 bg-gray-200 py-2 break-after-avoid",
          h3: "text-lg font-bold text-gray-800 mt-8 mb-4 underline decoration-orange-600 decoration-4 underline-offset-4 break-after-avoid",
          tableContainer: "my-10 w-full bg-[#1a1a1a] border-4 border-gray-800 rounded-lg shadow-xl overflow-x-auto",
          table: "w-full border-collapse text-left text-gray-300",
          tableHeader: "bg-gray-900 text-orange-500 uppercase text-xs tracking-widest border-b border-gray-700",
          tableTh: "px-5 py-3 border border-gray-700 align-top",
          tableBody: "divide-y divide-gray-800",
          tableRowEven: "bg-[#222222]",
          tableTd: "px-5 py-3 text-sm border border-gray-700 align-top leading-relaxed",
          keycap: "bg-[#333] border-gray-600 text-green-400 font-mono border-2",
          enterKey: "bg-orange-600 text-white border-orange-700",
          blockquote: "border-l-4 border-orange-600 bg-gray-200 text-gray-900 p-4 my-4 font-bold italic shadow-sm border-t border-b border-gray-300",
          code: "bg-black text-green-400 px-2 py-0.5 rounded text-sm font-mono border border-gray-700",
          strong: "text-orange-700 font-black",
          link: "text-orange-700 underline hover:text-orange-900",
          imagePlaceholder: "bg-gray-200 border-4 border-gray-400 p-6 my-6 flex flex-col items-center justify-center text-center hover:bg-orange-100 cursor-pointer group hover:border-orange-500 transition-colors"
        };
      case 'construction':
        return {
          wrapper: "font-sans",
          h1: "text-4xl font-black text-black border-b-[8px] border-yellow-400 pb-2 mb-8 uppercase tracking-tighter break-after-avoid",
          h2: "text-2xl font-bold bg-black text-yellow-400 px-6 py-3 mt-12 mb-6 inline-block uppercase transform -skew-x-6 shadow-[8px_8px_0px_0px_rgba(250,204,21,1)] break-after-avoid",
          h3: "text-lg font-bold text-black mt-8 mb-4 border-l-[10px] border-yellow-400 pl-3 uppercase break-after-avoid",
          tableContainer: "my-8 w-full border-4 border-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] bg-white overflow-x-auto",
          table: "w-full border-collapse text-left",
          tableHeader: "bg-yellow-400 text-black font-black uppercase text-sm border-b-4 border-black",
          tableTh: "px-4 py-3 border-2 border-black align-top",
          tableBody: "bg-white",
          tableRowEven: "bg-yellow-50",
          tableTd: "px-4 py-2 text-sm text-black font-bold border-2 border-black align-top leading-relaxed",
          keycap: "bg-black border-black text-yellow-400 font-black rounded-none shadow-[2px_2px_0px_0px_rgba(250,204,21,1)] border-b-0",
          enterKey: "bg-yellow-400 text-black border-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] border",
          blockquote: "bg-yellow-100 border-4 border-black p-6 my-6 font-bold text-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]",
          code: "bg-black text-yellow-400 px-2 py-0.5 font-mono text-sm font-bold",
          strong: "bg-yellow-300 px-1 text-black font-black box-decoration-clone",
          link: "text-black underline decoration-yellow-400 decoration-4 hover:bg-yellow-400 transition-colors",
          imagePlaceholder: "bg-yellow-50 border-4 border-black border-dashed p-8 my-8 flex flex-col items-center justify-center text-center font-bold text-black hover:bg-yellow-200 cursor-pointer group shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] hover:translate-x-[2px] hover:translate-y-[2px] transition-all"
        };
      case 'elegant':
        return {
          wrapper: "font-serif",
          h1: "text-4xl font-normal text-emerald-900 border-b border-emerald-200 pb-4 mb-8 italic text-center break-after-avoid",
          h2: "text-2xl font-normal text-emerald-800 mt-10 mb-6 flex items-center gap-2 break-after-avoid",
          h3: "text-xl font-medium text-emerald-700 mt-8 mb-4 italic break-after-avoid",
          tableContainer: "my-8 w-full border border-emerald-100 rounded-xl overflow-hidden shadow-lg bg-white overflow-x-auto",
          table: "w-full border-collapse text-left",
          tableHeader: "bg-emerald-50 text-emerald-900 font-medium tracking-wide border-b border-emerald-200",
          tableTh: "px-6 py-5 border border-emerald-100 align-top",
          tableBody: "bg-white",
          tableRowEven: "bg-[#fafcfb]",
          tableTd: "px-6 py-4 text-sm text-emerald-800 border border-emerald-100 align-top leading-relaxed",
          keycap: "bg-white border-emerald-200 text-emerald-800 rounded-md shadow-sm font-sans",
          enterKey: "bg-emerald-100 text-emerald-900 border-emerald-300",
          blockquote: "border-l-2 border-emerald-300 bg-emerald-50/50 text-emerald-800 p-6 my-6 italic text-lg relative",
          code: "bg-emerald-50 text-emerald-700 px-2 py-1 rounded border border-emerald-100 font-sans text-sm",
          strong: "text-emerald-900 font-semibold",
          link: "text-emerald-600 border-b border-emerald-300 hover:text-emerald-800 no-underline",
          imagePlaceholder: "bg-emerald-50/30 border border-emerald-200 p-8 my-8 flex flex-col items-center justify-center text-center rounded-lg hover:bg-emerald-100 cursor-pointer group hover:border-emerald-400 transition-colors"
        };
      case 'modern':
      default:
        return {
          wrapper: "font-sans",
          h1: "text-3xl font-bold text-brand-900 border-b-2 border-brand-100 pb-2 mb-6 break-after-avoid",
          h2: "text-2xl font-semibold text-brand-700 mt-10 mb-6 flex items-center break-after-avoid",
          h3: "text-lg font-semibold text-brand-600 mt-8 mb-4 break-after-avoid",
          tableContainer: "my-8 w-full border border-gray-200 rounded-lg overflow-hidden shadow-md bg-white ring-1 ring-gray-100 overflow-x-auto",
          table: "w-full border-collapse text-left",
          tableHeader: "bg-gray-50 text-brand-900",
          tableTh: "px-4 py-3 font-bold border border-gray-300 align-top tracking-wide text-xs uppercase text-gray-600",
          tableBody: "bg-white",
          tableRowEven: "bg-blue-50/20",
          tableTd: "px-4 py-2 text-sm text-gray-700 border border-gray-300 align-top leading-relaxed",
          keycap: "bg-white border-gray-200 text-gray-700 shadow-sm rounded border-b-2",
          enterKey: "bg-brand-50 border-brand-200 text-brand-600 font-bold",
          blockquote: "border-l-4 border-brand-400 bg-blue-50 text-brand-900 p-4 my-4 rounded-r-lg",
          code: "bg-gray-100 text-gray-800 px-1.5 py-0.5 rounded border border-gray-200 font-mono text-sm font-bold shadow-sm",
          strong: "text-brand-800 font-bold",
          link: "text-brand-600 hover:underline",
          imagePlaceholder: "bg-gray-50 border-2 border-dashed border-gray-300 p-8 my-6 flex flex-col items-center justify-center text-center rounded-lg hover:border-brand-400 hover:bg-white transition-all cursor-pointer group hover:shadow-sm"
        };
    }
  };

  const themeClasses = getThemeClasses();

  return (
    <div className="flex flex-col h-full bg-gray-100 print:bg-white print:h-auto print:block">
      {/* Toolbar - Same as before */}
      <div className="bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between shadow-sm no-print sticky top-0 z-10">
        <div className="flex items-center gap-4">
          <button 
            onClick={onBack}
            className="text-gray-500 hover:text-gray-800 flex items-center gap-1 text-sm font-medium"
          >
            <ArrowLeft className="w-4 h-4" />
            Späť
          </button>
          
          <div className="h-6 w-px bg-gray-300 mx-2 hidden sm:block"></div>

          <div className="flex items-center gap-2">
            <Palette className="w-4 h-4 text-gray-500" />
            <select
              value={theme}
              onChange={(e) => onThemeChange(e.target.value as ManualTheme)}
              disabled={isEditing}
              className="text-sm border-gray-300 border rounded-md shadow-sm py-1.5 pl-2 pr-8 bg-gray-50 cursor-pointer"
            >
              <option value="modern">Moderný (Modrý)</option>
              <option value="construction">Technický (Žltý)</option>
              <option value="industrial">Industrial (Terminál)</option>
              <option value="elegant">Elegantný (Zelený)</option>
              <option value="swiss">Swiss (Červený)</option>
            </select>
          </div>
        </div>
        
        <div className="flex gap-2">
           <button
            onClick={() => setIsEditing(!isEditing)}
            className={`flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-md border transition-colors ${
              isEditing 
                ? 'bg-yellow-100 text-yellow-800 border-yellow-300' 
                : 'bg-white text-gray-700 border-gray-300 hover:bg-gray-50'
            }`}
          >
            {isEditing ? <><Save className="w-4 h-4" /> Ukončiť úpravy</> : <><Edit3 className="w-4 h-4" /> Upraviť text</>}
          </button>
          
          <button
            onClick={handleSaveProject}
            disabled={isEditing}
            className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-brand-700 bg-brand-50 border border-brand-200 rounded-md hover:bg-brand-100 disabled:opacity-50"
          >
            <FolderDown className="w-4 h-4" />
            Uložiť Projekt
          </button>

          <button 
            onClick={handleDownloadMarkdown}
            disabled={isEditing}
            className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50"
          >
            <Download className="w-4 h-4" />
            Stiahnuť MD
          </button>
          <button 
            onClick={handlePrint}
            disabled={isEditing}
            className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-brand-600 rounded-md hover:bg-brand-700 shadow-sm disabled:opacity-50"
          >
            <Printer className="w-4 h-4" />
            Vytvoriť PDF
          </button>
        </div>
      </div>

      <div className={`flex-1 overflow-y-auto p-8 flex justify-center bg-gray-200 print:bg-white print:p-0 print:overflow-visible print:h-auto`}>
        
        {isEditing ? (
          <div className="w-full max-w-[210mm] h-full flex flex-col no-print">
            <div className="bg-gray-50 border border-gray-300 border-b-0 rounded-t-lg p-2 flex flex-wrap gap-2 items-center text-sm shadow-sm sticky top-0 z-10">
              <span className="text-gray-500 font-bold px-2 text-xs uppercase tracking-wider">Vložiť:</span>
              <button onClick={() => insertTextAtCursor(insertTemplates.tocTable)} className="px-3 py-1.5 bg-white border rounded hover:bg-gray-50 flex gap-1"><List className="w-4 h-4"/> Obsah</button>
              <button onClick={() => insertTextAtCursor(insertTemplates.menuTable)} className="px-3 py-1.5 bg-white border rounded hover:bg-gray-50 flex gap-1"><Grid className="w-4 h-4"/> Menu</button>
              <button onClick={() => insertTextAtCursor(insertTemplates.keypadTable)} className="px-3 py-1.5 bg-white border rounded hover:bg-gray-50 flex gap-1"><Terminal className="w-4 h-4"/> Klávesnica</button>
              <button onClick={() => insertTextAtCursor(insertTemplates.standardTable)} className="px-3 py-1.5 bg-white border rounded hover:bg-gray-50 flex gap-1"><Table className="w-4 h-4"/> Tabuľka</button>
              <button onClick={() => insertTextAtCursor(insertTemplates.imageJson)} className="px-3 py-1.5 bg-white border rounded hover:bg-gray-50 flex gap-1"><ImageIcon className="w-4 h-4"/> Obrázok (JSON)</button>
              <div className="h-4 w-px bg-gray-300 mx-1"></div>
              <button onClick={() => insertTextAtCursor(insertTemplates.alertInfo)} className="px-3 py-1.5 bg-white border rounded hover:bg-blue-50 flex gap-1 text-blue-600"><HelpCircle className="w-4 h-4"/> Info</button>
              <button onClick={() => insertTextAtCursor(insertTemplates.alertDanger)} className="px-3 py-1.5 bg-white border rounded hover:bg-red-50 flex gap-1 text-red-600"><AlertTriangle className="w-4 h-4"/> Pozor</button>
            </div>
            <textarea
              ref={textareaRef}
              value={content}
              onChange={(e) => onContentChange(e.target.value)}
              onPaste={handlePaste}
              className="w-full h-full min-h-[500px] p-12 font-mono text-sm bg-white border border-gray-300 shadow-xl resize-none focus:ring-2 focus:ring-brand-500 outline-none leading-relaxed"
              spellCheck={false}
            />
          </div>
        ) : (
          <div className="w-full flex flex-col items-center print:block print:w-full">
            {/* NEW: COVER PAGE */}
            <CoverPage theme={theme} title={brandName} date={new Date().toLocaleDateString('sk-SK')} />
            
            {/* THIS IS THE RENDERER */}
            <article className={`print-content prose max-w-none w-[210mm] min-h-[297mm] p-[20mm] bg-white shadow-2xl ${themeClasses.wrapper} print:shadow-none print:p-0 print:w-full print:max-w-none`}>
              <ReactMarkdown
                urlTransform={(url) => url} 
                components={{
                  pre: ({children}) => <>{children}</>,
                  code: ({node, className, children, ...props}) => {
                    const match = /language-([\w:.-]+)/.exec(className || '');
                    let type = match ? match[1] : '';
                    const contentStr = String(children);

                    if (type.includes('toc') || type.includes('menu') || type.includes('keypad') || type.includes('table') || type.includes('image')) {
                         try {
                             const jsonData = JSON.parse(contentStr);
                             if (type.includes('toc')) return <TocComponent data={jsonData} themeClasses={themeClasses} />;
                             if (type.includes('menu')) return <MenuComponent data={jsonData} themeClasses={themeClasses} />;
                             if (type.includes('keypad')) return <KeypadComponent data={jsonData} themeClasses={themeClasses} />;
                             if (type.includes('table')) return <TableComponent data={jsonData} themeClasses={themeClasses} />;
                             if (type.includes('image')) return <ImageBlockComponent data={jsonData} themeClasses={themeClasses} onUpload={(f) => handleSmartImageUpload(contentStr, f)} />;
                         } catch (e) {
                             return (
                                <div className="not-prose border border-red-300 bg-red-50 p-4 rounded my-4">
                                    <div className="text-red-600 text-sm font-bold mb-2 flex items-center gap-2">
                                      <AlertTriangle className="w-4 h-4"/> Chyba formátovania (Neplatný JSON)
                                    </div>
                                    <pre className="text-xs bg-red-100 p-2 overflow-x-auto text-red-800 rounded">{contentStr}</pre>
                                </div>
                             )
                         }
                    }
                    const isBlock = match !== null;
                    if (isBlock) {
                        return (
                          <pre className="not-prose my-6 w-full overflow-x-auto rounded bg-gray-900 p-4 text-sm text-white print:bg-gray-100 print:text-black print:border print:border-gray-300 break-inside-avoid page-break-inside-avoid">
                            <code className={className} {...props}>{children}</code>
                          </pre>
                        );
                    }
                    return <code className={themeClasses.code} {...props}>{children}</code>;
                  },
                  h1: ({node, ...props}) => <h1 className={`${themeClasses.h1}`} {...props} />,
                  h2: ({node, ...props}) => <h2 className={`${themeClasses.h2}`} {...props} />,
                  h3: ({node, ...props}) => <h3 className={`${themeClasses.h3}`} {...props} />,
                  p: ({node, ...props}) => <p className="mb-4 text-justify hyphens-auto" {...props} />,
                  ul: ({node, ...props}) => <ul className="list-disc pl-5 mb-4" {...props} />,
                  ol: ({node, ...props}) => <ol className="list-decimal pl-5 mb-4" {...props} />,
                  table: ({node, children, ...props}) => {
                    return (
                        <div className={`w-full ${themeClasses.tableContainer} manual-table-root`}>
                            <table className={themeClasses.table} {...props}>{children}</table>
                        </div>
                    );
                  },
                  thead: ({node, ...props}) => <thead className={themeClasses.tableHeader} {...props} />,
                  tbody: ({node, ...props}) => <tbody className={themeClasses.tableBody} {...props} />,
                  tr: ({node, ...props}) => <tr className={`even:${themeClasses.tableRowEven} border-b border-gray-200 last:border-0 break-inside-avoid page-break-inside-avoid`} {...props} />,
                  th: ({node, ...props}) => <th className={themeClasses.tableTh} {...props} />,
                  td: ({node, children, ...props}) => <td className={themeClasses.tableTd} {...props}>{children}</td>,
                  blockquote: ({node, children, ...props}) => {
                    const contentStr = String(children);
                    if (contentStr.includes('[!WARNING]')) {
                         return (
                            <div className="not-prose my-6 w-full p-4 border-l-8 border-red-500 bg-red-50 rounded-r shadow-sm flex gap-4 items-start print:bg-white print:border-red-600 break-inside-avoid page-break-inside-avoid">
                                <AlertTriangle className="w-6 h-6 text-red-600 shrink-0 mt-1" />
                                <div className="text-red-900 font-medium print:text-black">
                                    {contentStr.replace('[!WARNING]', '')}
                                </div> 
                            </div>
                         )
                    }
                    if (contentStr.includes('[!NOTE]')) {
                         return (
                            <div className="not-prose my-6 w-full p-4 border-l-8 border-blue-500 bg-blue-50 rounded-r shadow-sm flex gap-4 items-start print:bg-white print:border-blue-600 break-inside-avoid page-break-inside-avoid">
                                <HelpCircle className="w-6 h-6 text-blue-600 shrink-0 mt-1" />
                                <div className="text-blue-900 italic font-medium print:text-black">
                                    {contentStr.replace('[!NOTE]', '')}
                                </div>
                            </div>
                         )
                    }
                    return <blockquote className={`w-full ${themeClasses.blockquote} break-inside-avoid page-break-inside-avoid`} {...props}>{children}</blockquote>;
                  },
                  img: ({node, src, alt, ...props}) => {
                    return (
                      <div className="not-prose my-6 w-full flex flex-col items-center break-inside-avoid page-break-inside-avoid group relative image-block">
                        <img 
                          src={src} 
                          alt={alt}
                          {...props} 
                          className="max-w-full max-h-[100mm] object-contain border border-gray-200 rounded-sm shadow-sm" 
                        />
                        <label className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity print:hidden cursor-pointer">
                          <div className="bg-white/90 backdrop-blur-sm p-2 rounded-full shadow-md border border-gray-300 hover:bg-white text-gray-700 hover:text-brand-600">
                             <RefreshCw className="w-4 h-4" />
                          </div>
                          <input 
                            type="file" 
                            accept="image/*" 
                            className="hidden" 
                            onChange={(e) => {
                                if (e.target.files?.[0] && src) {
                                   handleReplaceImage(src, e.target.files[0]);
                                }
                            }} 
                          />
                        </label>
                      </div>
                    )
                  },
                  strong: ({node, ...props}) => <strong className={themeClasses.strong} {...props} />,
                  a: ({node, ...props}) => <a className={themeClasses.link} {...props} />,
                  hr: ({node, ...props}) => (
                     <>
                        <div className="not-prose h-12 bg-gray-200 border-none relative flex items-center justify-center print:hidden -mx-[20mm] my-[20mm] shadow-inner">
                           <span className="bg-gray-200 px-4 text-gray-400 text-xs font-mono uppercase">Koniec strany</span>
                        </div>
                        <div className="page-break-always"></div>
                     </>
                  )
                }}
              >
                {safeContent}
              </ReactMarkdown>

               {/* REMOVED PRINT FOOTER */}
            </article>
            <div className="mt-12 pt-6 border-t border-gray-200 flex justify-between text-xs text-gray-400 print:hidden w-full max-w-[210mm]">
              <span>Elift Documentation</span>
              <span>{new Date().toLocaleDateString('sk-SK')}</span>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ManualPreview;